# Generated by Django 5.2.5 on 2025-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="imageUrl",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/images/project1/"
            ),
        ),
    ]
